version: "3"

services:
  application:
    container_name: graphql-server
    image: docker.pkg.github.com/zobairq/interview-assignment/graphql-server:latest
    ports:
      - 4000:4000
    depends_on:
      - mysql
    environment:
      PORT: $PORT
      HOST: $HOST
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_NAME: $DATABASE_NAME
      DIALECT: $DIALECT

  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: cego
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - type: bind
        source: "$DUMP_SOURCE"
        target: "$DUMP_TARGET"
      - type: volume
        source: persistance
        target: $PERSISTANCE_TARGET

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8000:80
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
      PMA_PORT: 3306

volumes:
  persistance:
